Pipfile.lock, src/api/models.py
=> [Implemente Tabla USER]

src/api/models.py
Se agrego tabla reservation y se actualizo el serialize
=> Martin cedres implementar tabla users

src/api/routes.py, src/app.py
Se implementaron varias funcionalidades relacionadas con la autenticación de usuarios y la gestión de estados:
- **Endpoints**:
- Registro de usuarios: Permite a los usuarios registrarse con un estado inicial "en revisión".
- Login de usuarios: Valida credenciales y genera tokens JWT para acceso.
- Gestión por administradores: 
- Aprobación de usuarios pendientes.
- Visualización de usuarios con estado "en revisión".
- **Configuraciones adicionales**:
- Contraseñas hasheadas utilizando `Flask-Bcrypt` para mayor seguridad.
- Tokens configurados con expiración personalizada (1 año) mediante `Flask-JWT-Extended`.
- Rutas protegidas que requieren autenticación mediante JWT.
=> Implementación de autenticación JWT y manejo de estados de usuarios

src/api/models.py
E implemente relacion entre las tablas User, reservations y boock_reservations
=> CREE TABLA BOOCK_RESERVATIONS

src/front/js/component/navbar.js, src/front/js/component/sidebar.js, src/front/js/layout.js, src/front/js/pages/AdministradorUsuarios.js, src/front/js/pages/EditarCargarLibro.js, src/front/js/pages/EditarCargarSalon.js, src/front/js/pages/SubirLibro.js, src/front/js/pages/TuPerfil.js, src/front/styles/index.css, template.html
Kafalara- Se creo las vistas de Perfil, EditarCargarLibro, EditarCargarSalon, AdministradorUsuarios, navbar. Queda pendiente hacer los fetch.
=> [Cree vista de panel de administrador]

src/api/routes.py, src/app.py
- Añadidos endpoints en routes.py para la gestión de libros:
* `GET /api/books`: Listar todos los libros disponibles.
* `GET /api/books/:id`: Obtener detalles de un libro específico.
* `POST /api/books`: Agregar un nuevo libro (solo admin).
* `PUT /api/books/:id`: Editar información de un libro (solo admin).
* `DELETE /api/books/:id`: Eliminar un libro del catálogo (solo admin).
- Ajustes en app.py:
* Movidos los endpoints de login y register desde routes.py a app.py para evitar conflictos y mejorar la organización.
- Mejoras generales:
* Implementada la importación de `from dotenv import load_dotenv` para cargar las configuraciones desde `.env` de forma segura.
* Ahora la clave JWT y la URL de la base de datos se manejan a través de variables de entorno.
=> [Implementación endpoints para gestión de libros]

src/api/routes.py
Descripción:
Se implementaron dos endpoints para gestionar las reservas de libros en la biblioteca. Estos endpoints permiten a los usuarios realizar y gestionar reservas de manera eficiente, garantizando la disponibilidad de los libros.
Cambios realizados:
- Añadido endpoint POST /book-reservations:
* Permite a los usuarios reservar un libro específico.
* Valida que el libro exista y esté disponible.
* Crea una nueva reserva en la tabla `Books_reservations`.
* Marca el libro como no disponible (`availability = False`).
- Añadido endpoint PUT /book-reservations/:id:
* Permite marcar un libro como devuelto.
* Valida que la reserva y el libro existan.
* Actualiza el campo `returned_at` en la reserva.
* Marca el libro como disponible (`availability = True`).
Notas adicionales:
- Los endpoints …
=> [Creación de endpoints reservas de libros]

src/api/routes.py
- Añadidos nuevos endpoints para gestionar perfiles de usuario en el archivo `routes.py`:
* `GET /user-profiles`: Obtener todos los perfiles (solo para administradores).
* `GET /user-profiles/<int:user_id>`: Obtener un perfil específico por ID.
* `POST /user-profiles`: Crear un nuevo perfil.
* `PUT /user-profiles/<int:user_id>`: Actualizar un perfil existente.
- Nota: Se espera por el PR de implementación de la tabla `user_profiles` para completar el flujo de datos.
=> [Implementación endpoints user_profiles]

Pipfile, Pipfile.lock, src/api/models.py
Actualice png base_datos
Se agrego tabla UserProfiles
Agregue validación de correos electronicos en models.py para que solo acepte correos con dominio @anda.com.uy en tablas User y UserProfiles
Se agregaron migraciones para la tabla UserProfiles
=> Agregar tabla UserProfiles. Migraciones 

Pipfile, Pipfile.lock, src/api/models.py, src/api/routes.py
- Implementación de la librería Pendulum para el manejo de fechas y horas en `models.py` y `routes.py`.
- Reemplazo de `datetime` y `pytz` con una función `lazy_utc_now` basada en Pendulum en los modelos.
- Ajustes en los modelos para usar la nueva función `lazy_utc_now` en los campos `created_at` y `updated_at`.
- Configuración de las migraciones de base de datos para reflejar los cambios en los modelos.
- Asegurada la compatibilidad con la estructura existente del backend.
=> [implementado manejo de fechas con Pendulum]

src/front/js/index.js, src/front/js/layout.js, src/front/js/pages/About.js, src/front/js/pages/home.js
Envolvi el componente Layout con BrowserRouter en el archivo index.js. para que los hooks como useLocation puedan acceder correctamente a las rutas.
Realice cambios en Home y About para que se ajusten a Figma
=> Implemente Logica Nabvar

src/app.py, src/front/js/layout.js, src/front/js/pages/About.js, src/front/js/store/appContext.js, src/front/js/store/flux.js
=> Cree Componente protectedRoute modifique layout con rutas protegidas

src/api/models.py, src/app.py
Cambios realizados:
Refactorización de la tabla user:
Se renombró la tabla user a users en el modelo User utilizando __tablename__ para resolver conflictos con SQL y asegurar consistencia en las migraciones. Se realizaron ajustes en todas las relaciones (ForeignKey y relationship) dependientes de la tabla user para reflejar el cambio a users.
Actualización de migraciones:
Inicialización de las migraciones del proyecto con pipenv run init-db. Creación de una nueva migración para reflejar el cambio de nombre de la tabla y la estructura actualizada de la base de datos. Ejecución de las migraciones con pipenv run upgrade para aplicar los cambios a la base de datos.
Corrección en el entorno de desarrollo:
Configuración y ejecución de los comandos de migración utilizando pipenv para garantizar …
=> [Refactorización de modelos y corrección de migraciones con Pipenv]

src/api/routes.py, src/app.py, src/front/js/component/login.js, src/front/js/component/register.js, src/front/js/store/flux.js
- Añadidos endpoints para login y registro en el backend.
- Conexión del frontend con el backend para login y registro.
- Mejoras en las funciones de manejo de formularios en el frontend.
- Integración de la lógica de autenticación con JWT en `flux.js`.
Lista para pruebas adicionales de flujos autenticados.
=> [Implementación de autenticación inicial]

src/front/js/component/FirstEventView.js, src/front/js/component/SecondEventView.js
-MicaelaDeRosa , se hizo la home de eventos y de resrva de salon
=> [Cree las dos vistas de eventos]

package-lock.json, src/front/js/component/SidebarUser.js, src/front/js/pages/PanelUsuario.js
* Últimos detalles para SidebarUser.js y PanelUsuario.js
=> Checkpoint 15.12.24 - 23:40 pm

src/api/models.py, src/api/routes.py, src/front/js/component/LibroCard.js, src/front/js/pages/Biblioteca.js, src/front/js/pages/EditarCargarLibro.js, src/front/js/pages/Reservas.js, src/front/js/pages/SubirLibro.js, src/front/js/store/appContext.js, src/front/js/store/flux.js
- Actualización de modelos y rutas en el backend.
- Implementación de manejo de reservas y detalles de libros en el frontend. 
- Ajustes en los componentes Reservas, Biblioteca, EditarCargarLibro y SubirLibro. 
- Actualización de store y appContext para sincronizar datos con el backend.
=> [Integración de funcionalidades de biblioteca]

src/front/js/layout.js, src/front/js/pages/TuPerfilUser.js, src/front/js/store/flux.js
- Se agregaron los endpoints de perfiles en flux.js.
=> [Integración de Endpoints de Perfiles user/admin]

src/front/js/component/LibroCard.js, src/front/js/component/PanelAdministrador.js, src/front/js/component/Sidebar.js, src/front/js/component/SidebarUser.js, src/front/js/component/navbar.js, src/front/js/layout.js, src/front/js/pages/ModificarLibro.js, src/front/js/pages/PanelUsuario.js
kafalara:navbar ajustes en redirecciones según rol. navbar: accion de cerrar sesión y perfil
Sidebar: ajustes por rol.
layout: incorporación de ModificarLibro
PanelUsuario: que permita modificar los datos
LibroCard: redireccionamiento del boton modificar a ModificarLibro
=> [Ajustes en vistas]

package-lock.json, package.json, src/api/routes.py, src/front/js/component/LibroCard.js, src/front/js/component/login.js, src/front/js/component/register.js, src/front/js/layout.js, src/front/js/pages/EditarCargarLibro.js, src/front/js/pages/Reservas.js, src/front/js/pages/SubirLibro.js, src/front/js/store/flux.js
kafalara- Se incorporó las notificaciones con Sonner. kafalara- flux: se hizo un ajuste en reservar libro.
=> [Incorporacion de Notificaciones y ajuste reserva libros]

.vscode/settings.json, src/api/models.py, src/api/routes.py, src/front/js/component/LibroCard.js, src/front/js/pages/SubirLibro.js, src/front/js/store/flux.js
SubirLibro: se incorporo cloudinary para cargar imagen en la vista SubirLibro
=> [Incorporación de miniatura en SubirLibro]

src/front/js/component/SecondEventView.js, src/front/js/component/SidebarUser.js, src/front/js/layout.js, src/front/js/pages/CalendarioEventosUser.js, src/front/js/pages/Reservas.js, src/front/js/pages/TuPerfilUser.js
kafalara: Se utilizó sonner para las notificaciones.
=> [Sumar notificaciones y ajustes varios]
